server:
    port: 8080

spring:
    application:
        name: blogapp
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./blogdb;
    jpa:
        hibernate:
            ddl-auto: create # in prod - use update

